# Generated by Django 5.0.1 on 2024-09-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminpanelApp', '0006_instructorfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
