# Generated by Django 5.0.1 on 2024-09-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminpanelApp', '0007_course_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.RemoveField(
            model_name='instructorfeedback',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructorfeedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='MediaLibrary',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.DeleteModel(
            name='AdminMessage',
        ),
        migrations.DeleteModel(
            name='InstructorFeedback',
        ),
    ]
