# Generated by Django 5.0.1 on 2024-09-24 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminpanelApp', '0008_remove_adminmessage_sender_delete_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_instructor', to='AdminpanelApp.instructor'),
        ),
    ]
