# Generated by Django 5.0.1 on 2025-07-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminpanelApp', '0015_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
