# Generated by Django 5.0.1 on 2025-07-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminpanelApp', '0016_lesson_is_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
